--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025. 11. 10. 11:45:57
-- Server version: 8.0.28
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8mb4';

--
-- Set default database
--
USE orszagok;

--
-- Drop table `orszagok`
--
DROP TABLE IF EXISTS orszagok;

--
-- Set default database
--
USE orszagok;

--
-- Create table `orszagok`
--
CREATE TABLE orszagok (
  id int NOT NULL AUTO_INCREMENT,
  kod char(2) NOT NULL,
  nev varchar(100) NOT NULL,
  regio varchar(50) NOT NULL DEFAULT 'Europa',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 45,
AVG_ROW_LENGTH = 431,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table orszagok
--
INSERT INTO orszagok VALUES
(7, 'BG', 'Bulgária', 'Európa'),
(8, 'HR', 'Horvátország', 'Európa'),
(9, 'CY', 'Ciprus', 'Európa'),
(10, 'CZ', 'Csehország', 'Európa'),
(11, 'DK', 'Dánia', 'Európa'),
(12, 'EE', 'Észtország', 'Európa'),
(13, 'FI', 'Finnország', 'Európa'),
(14, 'FR', 'Franciaország', 'Európa'),
(15, 'DE', 'Németország', 'Európa'),
(16, 'GR', 'Görögország', 'Európa'),
(17, 'HU', 'Magyarország', 'Európa'),
(18, 'IS', 'Izland', 'Európa'),
(19, 'IE', 'Írország', 'Európa'),
(20, 'IT', 'Olaszország', 'Európa'),
(21, 'LV', 'Lettország', 'Európa'),
(22, 'LT', 'Litvánia', 'Európa'),
(23, 'LU', 'Luxemburg', 'Európa'),
(24, 'MT', 'Málta', 'Európa'),
(25, 'MD', 'Moldova', 'Európa'),
(26, 'MC', 'Monaco', 'Európa'),
(27, 'ME', 'Montenegró', 'Európa'),
(28, 'NL', 'Hollandia', 'Európa'),
(29, 'MK', 'Észak-Macedónia', 'Európa'),
(30, 'NO', 'Norvégia', 'Európa'),
(31, 'PL', 'Lengyelország', 'Európa'),
(32, 'PT', 'Portugália', 'Európa'),
(33, 'RO', 'Románia', 'Európa'),
(34, 'RU', 'Oroszország', 'Európa'),
(35, 'RS', 'Szerbia', 'Európa'),
(36, 'SK', 'Szlovákia', 'Európa'),
(37, 'SI', 'Szlovénia', 'Európa'),
(38, 'ES', 'Spanyolország', 'Európa'),
(39, 'SE', 'Svédország', 'Európa'),
(40, 'CH', 'Svájc', 'Európa'),
(41, 'UA', 'Ukrajna', 'Európa'),
(42, 'GB', 'Egyesült Királyság', 'Európa'),
(43, 'VA', 'Vatikánváros', 'Európa'),
(44, 'LI', 'Libia', 'Afrika');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;